---
run:
  deadline: 30m

linters:
  enable-all: true
  disable:
    - gochecknoglobals  # unreliable
    - golint            # covered by revive
    - interfacer        # deprecated
    - lll               # line length check
    - stylecheck        # covered by revive
    - typecheck         # See golangci/golangci-lint#419
    - varcheck          # unreliable

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
